version: '3.3'

services:
  test-app:
    image: esignet-bb-identity-api-image
    ports:
      - 3333:3001
    networks:
      - web
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./esignet-bbidentity.json:/esignet-bbidentity.json

networks:
  web:
    driver: bridge
